namespace QueryProvider.SqlServer.QueryBase
{
    public class DynamicFormQueryBase : QueryBase
    {
        public DynamicFormQueryBase()
        {
            Add("FormConfiguration", "Select * from FormConfiguration where FormConfigId = @FormConfigId");
            Add("FormFieldConfiguration", @"Select Name,Label,Type,Placeholder,SearchOperator,IsUpdatable,ObjectId,CatId,MaxDate,MinDate,DisplayFormat,
                    IsRequired, MaxValue, MinValue, Pattern, IsPrimaryKey, IsAutoGenerated from FormFieldConfiguration
                    where FormConfigId = @FormConfigId order by [Sequence]");
        }
    }
}
