using BizOS.Common.Contracts.Constants;
using QueryProvider.Contracts.Common;

namespace QueryProvider.SqlServer.QueryBase
{
    public class DynamicFormQueryProvider : IDynamicFormQueryProvider
    {
        public string FormConfiguration { get; }
        public string FormFieldConfiguration { get; }
        public DynamicFormQueryProvider()
        {
            FormConfiguration = "Select * from FormConfiguration where FormConfigId = @FormConfigId";
            FormFieldConfiguration = @"Select Name,Label,Type,Placeholder,SearchOperator,IsUpdatable,ObjectId,CatId,MaxDate,MinDate,DisplayFormat,
                    IsRequired, MaxValue, MinValue, Pattern, IsPrimaryKey, IsAutoGenerated from FormFieldConfiguration
                    where FormConfigId = @FormConfigId order by [Sequence]";
        }

    }
}
