using Core.Common.Contracts.DynamicForm;
using Core.Common.Contracts.DynamicForm.Models;
using Framework.Base.BL.DataAccess;
using System.Collections.Generic;
using System;
using Dapper;
using System.Linq;
using System.Text;
using Core.Common.Extensions;

namespace Core.Common.Repository.DynamicForm
{
    internal class DynamicFormRepository : BaseRepository, IDynamicFormRepository
    {

        string formFieldConfigurationSelectSql = @"Select Name,Label,Type,Placeholder,SearchOperator,IsUpdatable,ObjectId,CatId,MaxDate,MinDate,DisplayFormat,
                    IsRequired,MaxValue,MinValue,Pattern, IsPrimaryKey, IsAutoGenerated from FormFieldConfiguration 
                    where FormConfigId = @FormConfigId";
        public List<FormFieldConfiguration> GetFormControls(string FormConfigId)
        {
            return Connection.Query<FormFieldConfiguration, CatalogFieldConfig, DatetimeFieldConfig, Validations, FormFieldConfiguration>(
                formFieldConfigurationSelectSql,
                (catalogFormConfiguration, catalogFieldConfig, datetimeFieldConfig, validations) => {
                    catalogFormConfiguration.CustomValidation = validations;
                    catalogFormConfiguration.TypeaheadOptions = catalogFieldConfig;
                    catalogFormConfiguration.DatetimePickerOptions = datetimeFieldConfig;
                    return catalogFormConfiguration;
                },
                new { FormConfigId = FormConfigId },
                splitOn : "CatId,MaxDate,IsRequired").AsList();
        }

        public FormConfiguration GetFormConfig(string FormConfigId)
        {
            string sql = @"Select * from FormConfiguration 
                    where FormConfigId = @FormConfigId";
            return Connection.Query<FormConfiguration>(sql, new { FormConfigId = FormConfigId }).FirstOrDefault();
        }

        public override object GetPocoObject<T>(T Model)
        {
            return Model;   
        }

        public bool Create(string FormConfigId, Dictionary<string, object> formData)
        {
            bool isSaved = false;
            if (FormConfigId.IsNotNullOrEmpty() && formData.IsNotNullOrEmpty())
            {
                string tableName = GetTableName(FormConfigId);
                if (tableName.IsNotNullOrEmpty())
                {
                    List<FormFieldDBConfiguration> controlsDBConfig = GetFormControlsDBConfig(FormConfigId);
                    controlsDBConfig = controlsDBConfig.Where(control => formData.Keys.Contains(control.Name)).ToList();
                    if (controlsDBConfig.IsNotNullOrEmpty())
                    {
                        string insertQuery = BuildInsertQuery(tableName, controlsDBConfig);
                        object parameters = formData.ToDynamicObject();
                        int rowsInserted = Connection.Execute(insertQuery, parameters);
                        isSaved = rowsInserted > 0;
                    }
                }
            }
            return isSaved;
        }
        public bool Update(string FormConfigId, Dictionary<string, object> formData)
        {
            bool isSaved = false;
            if (FormConfigId.IsNotNullOrEmpty() && formData.IsNotNullOrEmpty())
            {
                string tableName = GetTableName(FormConfigId);
                if (tableName.IsNotNullOrEmpty())
                {
                    List<FormFieldDBConfiguration> controlsDBConfig = GetFormControlsDBConfig(FormConfigId);
                    controlsDBConfig = controlsDBConfig.Where(control => formData.Keys.Contains(control.Name)).ToList();
                    if (controlsDBConfig.IsNotNullOrEmpty())
                    {
                        string query = BuildUpdateQuery(tableName, controlsDBConfig);
                        object parameters = formData.ToDynamicObject();
                        int rowsInserted = Connection.Execute(query, parameters);
                        isSaved = rowsInserted > 0;
                    }
                }
            }
            return isSaved;
        }
        public bool Delete(string FormConfigId, Dictionary<string, object> formData)
        {
            bool isSaved = false;
            if (FormConfigId.IsNotNullOrEmpty() && formData.IsNotNullOrEmpty())
            {
                string tableName = GetTableName(FormConfigId);
                if (tableName.IsNotNullOrEmpty())
                {
                    List<FormFieldDBConfiguration> controlsDBConfig = GetFormControlsDBConfig(FormConfigId);
                    controlsDBConfig = controlsDBConfig.Where(control => formData.Keys.Contains(control.Name)).ToList();
                    if (controlsDBConfig.IsNotNullOrEmpty())
                    {
                        string query = BuildDeleteQuery(tableName, controlsDBConfig);
                        object parameters = formData.ToDynamicObject();
                        int rowsInserted = Connection.Execute(query, parameters);
                        isSaved = rowsInserted > 0;
                    }
                }
            }
            return isSaved;
        }
        private string BuildDeleteQuery(string tableName, List<FormFieldDBConfiguration> controlsDBConfig)
        {
            string deleteQuey = string.Empty;
            if (tableName.IsNotNullOrEmpty() && controlsDBConfig.IsNotNullOrEmpty())
            {
                string conditions = GetConditionOfPrimaryKey(controlsDBConfig);
                StringBuilder queryBuilder = new StringBuilder();
                queryBuilder.Append("Delete ");
                queryBuilder.Append(tableName);
                queryBuilder.Append(" where ");
                queryBuilder.Append(conditions);
                deleteQuey = queryBuilder.ToString();
            }
            return deleteQuey;
        }
        private string BuildUpdateQuery(string tableName, List<FormFieldDBConfiguration> controlsDBConfig)
        {
            string updateQuey = string.Empty;
            if (tableName.IsNotNullOrEmpty() && controlsDBConfig.IsNotNullOrEmpty())
            {
                List<FormFieldDBConfiguration> updateColumnDBConfig = controlsDBConfig.Where(control => !control.DBAttributes.IsAutoGenerated && !control.DBAttributes.IsPrimaryKey).ToList();
                string columns = string.Join(",", updateColumnDBConfig.Select(control => control.Name + " = @" +control.Name ).ToList());
                string conditions = GetConditionOfPrimaryKey(controlsDBConfig);
                StringBuilder queryBuilder = new StringBuilder();
                queryBuilder.Append("Update ");
                queryBuilder.Append(tableName);
                queryBuilder.Append(" set ");
                queryBuilder.Append(columns);
                queryBuilder.Append(" where ");
                queryBuilder.Append(conditions);
                updateQuey = queryBuilder.ToString();
            }
            return updateQuey;
        }
        private string GetConditionOfPrimaryKey(List<FormFieldDBConfiguration> controlsDBConfig)
        {
            List<FormFieldDBConfiguration> conditionColumnDBConfig = controlsDBConfig.Where(control => control.DBAttributes.IsPrimaryKey).ToList();
            return string.Join(" And ", conditionColumnDBConfig.Select(control => control.Name + " = @" + control.Name).ToList());
        }
        private string BuildInsertQuery(string tableName, List<FormFieldDBConfiguration> controlsDBConfig)
        {
            string insertQuery = string.Empty;
            if (tableName.IsNotNullOrEmpty() && controlsDBConfig.IsNotNullOrEmpty())
            {
                controlsDBConfig = controlsDBConfig.Where(control => !control.DBAttributes.IsAutoGenerated).ToList();
                string columns = string.Join(",", controlsDBConfig.Select(control => control.Name).ToList());
                string columnParams = string.Join(",", controlsDBConfig.Select(control => "@"+control.Name).ToList());

                StringBuilder queryBuilder = new StringBuilder();
                queryBuilder.Append("Insert into ");
                queryBuilder.Append(tableName);
                queryBuilder.Append(" (");
                queryBuilder.Append(columns);
                queryBuilder.Append(" ) Values ( ");
                queryBuilder.Append(columnParams);
                queryBuilder.Append(" )");
                insertQuery = queryBuilder.ToString();
            }
            return insertQuery;

        }
        private string GetTableName(string FormConfigId)
        {
            string sql = @"Select TableName from FormConfiguration 
                    where FormConfigId = @FormConfigId";
           return Connection.ExecuteScalar<string>(sql, new { FormConfigId = FormConfigId });
        }
        private List<FormFieldDBConfiguration> GetFormControlsDBConfig(string FormConfigId)
        {
            return Connection.Query<FormFieldDBConfiguration, Validations, DatabaseAttributes, FormFieldDBConfiguration>(
                formFieldConfigurationSelectSql,
                (catalogFormConfiguration, validations,dbAttributes ) => {
                    catalogFormConfiguration.CustomValidation = validations;
                    catalogFormConfiguration.DBAttributes = dbAttributes;
                    return catalogFormConfiguration;
                },
                new { FormConfigId = FormConfigId },
                splitOn: "CatId,IsRequired,IsPrimaryKey").AsList();
        }
    }
}
