Drop Table [GridColumnConfiguration]
Drop Table [SqlSourceConfiguration]
Drop Table [GridConfiguration]
Drop Table [FormFieldConfiguration]
Drop Table [CatalogDictionary]
Drop Table [FormConfiguration]
Drop Table [ModuleMenu]
Drop Table [ModuleCatalog]


CREATE TABLE ModuleCatalog
(
	ModuleId VARCHAR(25) CONSTRAINT PK_ModuleConfiguration PRIMARY KEY,
	ModuleName VARCHAR(25) NOT NULL,
	IsActivated BIT NOT NULL
)
CREATE TABLE ModuleMenu
(
	MenuId int CONSTRAINT PK_ModuleMenu PRIMARY KEY,
	ModuleId VARCHAR(25) CONSTRAINT FK_ModuleCatalog_ModuleMenu REFERENCES ModuleCatalog(ModuleId),
	ParentId int CONSTRAINT FK_ModuleMenu_ModuleMenu REFERENCES ModuleMenu(MenuId),
	[Name] VARCHAR(25) NOT NULL,
	Config VARCHAR(1000)
)

CREATE TABLE CatalogDictionary
(
	CatalogId VARCHAR(20) CONSTRAINT PK_CatalogDictionary PRIMARY KEY,
	TableName VARCHAR(250),
	DisplayColumn VARCHAR(50),
	ValueColumn VARCHAR(50),
	Condition VARCHAR(1000),
	ObjectId RowVersion
)
CREATE TABLE FormConfiguration
(
	FormConfigId VARCHAR(20) NOT NULL CONSTRAINT PK_FormConfiguration PRIMARY KEY ,
	TableName VARCHAR(150) NOT NULL,
	GridConfigId VARCHAR(20),
	FormName VARCHAR(50) NOT NULL,
	RowId UniqueIdentifier NOT NULL,
	ObjectId RowVersion
)
CREATE TABLE FormFieldConfiguration
(
	FormConfigId VARCHAR(20) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	Label VARCHAR(50) NOT NULL,
	[Type] VARCHAR(50) NOT NULL,
	Placeholder varchar(50),
	CatId VARCHAR(20) Constraint FK_FormFieldConfiguration_CatalogDictionary_CatId References CatalogDictionary(CatalogId) ,
	MaxDate Datetime,
	MinDate Datetime,
	DisplayFormat Varchar(23),
	IsRequired BIT,
	MaxValue VARCHAR(50),
	MinValue VARCHAR(50),
	Pattern VARCHAR(250),
	SearchOperator Varchar(20),
	IsPrimaryKey BIT,
	IsAutoGenerated	 BIT,
	IsUpdatable BIT, 
	ObjectId RowVersion,
	[Sequence] int,
	CONSTRAINT PK_FormFieldConfiguration PRIMARY KEY (FormConfigId, Name),
	CONSTRAINT UK_FormFieldConfiguration_FieldName UNIQUE (FormConfigId,Label),
)
CREATE TABLE GridConfiguration
(
	GridConfigId varchar(20) CONSTRAINT PK_GridConfiguration PRIMARY KEY,
	PageSize int,
	SearchConfigId varchar(20)  Constraint FK_GridConfiguration_FormConfiguration_SearchConfigId References FormConfiguration(FormConfigId),
	Url varchar(250),
	Method varchar(10),
	Params varchar(max),
	TableName varchar(max),
	ColumnList varchar(max)
)
CREATE TABLE SqlSourceConfiguration
(
	GridConfigId varchar(20) CONSTRAINT PK_SqlSourceConfiguration PRIMARY KEY Constraint FK_SqlSourceConfiguration_GridConfiguration References GridConfiguration(GridConfigId),
	SqlQuery varchar(max) NOT NULL,
	SqlSourceType int NOT NULL CHECK (SqlSourceType In(10,20)) DEFAULT 10,
	Condition VARCHAR(max)
)
CREATE TABLE GridColumnConfiguration
(
	GridConfigId varchar(20) CONSTRAINT FK_GridColConfiguration_GridConfiguration_GridConfigId REFERENCES GridConfiguration(GridConfigId),
	DataField Varchar(20) NOT NULL,
    DataType varchar(20) NOT NULL,
	Header varchar(150),
	Formatter VARCHAR(100),
    ColSpan int,
    DefaultValue varchar(20),
    CssClass Varchar(50),
    Sortable bit,
    SortOrder varchar(4),
    Width int,
    Align varchar(10),
	CONSTRAINT PK_GridColumnConfiguration PRIMARY KEY (GridConfigId,DataField)
)
