namespace BizOS.Common.Contracts.DynamicForm.Models
{
    public class DatabaseAttributes
    {
        public bool IsPrimaryKey { get; set; }
        public bool IsAutoGenerated { get; set; }
    }
}
